# Generated by Django 4.2.17 on 2025-12-01 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coursesemester", "0002_auto_20210202_0225"),
        ("tutoring", "0003_auto_20221128_1703"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutoringAvailability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Mon"),
                            (1, "Tue"),
                            (2, "Wed"),
                            (3, "Thu"),
                            (4, "Fri"),
                            (5, "Sat"),
                            (6, "Sun"),
                        ]
                    ),
                ),
                (
                    "hour",
                    models.IntegerField(
                        choices=[
                            (12, "12 PM"),
                            (13, "1 PM"),
                            (14, "2 PM"),
                            (15, "3 PM"),
                            (16, "4 PM"),
                        ]
                    ),
                ),
                (
                    "preference_level",
                    models.IntegerField(
                        choices=[
                            (0, "Cannot make it"),
                            (1, "Less preferred but can make it"),
                            (2, "Can make it"),
                            (3, "Preferred"),
                        ],
                        default=0,
                    ),
                ),
                ("cory_preference", models.BooleanField(default=True)),
                ("soda_preference", models.BooleanField(default=True)),
                (
                    "adjacent_slots_preference",
                    models.IntegerField(
                        choices=[
                            (-1, "Don't care"),
                            (0, "Prefer not adjacent"),
                            (1, "Prefer adjacent"),
                        ],
                        default=-1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coursesemester.semester",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutoring_availability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "hour"],
                "unique_together": {("user", "semester", "weekday", "hour")},
            },
        ),
    ]
