# Generated by Django 4.2.17 on 2025-12-01 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coursesemester", "0002_auto_20210202_0225"),
        ("tutoring", "0004_tutoringavailability"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tutoringavailability",
            unique_together={("user", "weekday", "hour")},
        ),
        migrations.AlterField(
            model_name="tutoringavailability",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coursesemester.semester",
            ),
        ),
    ]
